<?php

return [

    'stopwords' => [
        'na', 'ng', 'sa', 'ang', 'mga', 'nga', 'nang', 'ay', 'at',
        'the', 'a', 'an', 'of', 'from', 'and', 'or', 'for', 'to', 'in', 'on',
        'with', 'without', 'not', 'ko', 'og', 'kay', 'ra', 'lang', 'po',
        'yung', 'ka', 'mo', 'my', 'is', 'it', 'be', 'dili', 'hindi', 'walay',
        'that', 'this', 'nga',
    ],

    'brands' => [
        'bear brand',
        'coca-cola',
        'coca cola',
        'del monte',
        'lucky me',
        'nestle',
        'alaska',
        'magnolia',
        'selecta',
        'coke',
        'sprite',
        'pepsi',
        'nissin',
    ],

    'price_cheap' => ['barato', 'mura', 'cheap', 'affordable', 'budget', 'mura ra'],

    'price_premium' => ['premium', 'mahal', 'expensive', 'imported'],

    'dietary' => [
        'vegan' => ['vegan'],
        'plant-based' => ['plant-based', 'plant based', 'oat', 'soy', 'almond'],
        'non-cow' => ['non-cow', 'goat', 'kambing'],
        'non-dairy' => ['non-dairy', 'dairy-free', 'dairy free'],
    ],

    /*
    | Local shopper words (Bisaya, Tagalog, or mixed) mapped to the English
    | product name used in the catalog. Longest phrase wins.
    */
    'canonical_products' => [
        'soy sauce' => 'soy sauce',
        'toyo' => 'soy sauce',
        'tuyo' => 'soy sauce',
        'suka' => 'vinegar',
        'vinegar' => 'vinegar',
        'patis' => 'fish sauce',
        'fish sauce' => 'fish sauce',
        'dried herring' => 'dried fish',
        'dried fish' => 'dried fish',
        'bulad' => 'dried fish',
        'daing' => 'dried fish',
        'gatas' => 'milk',
        'milk' => 'milk',
        'bugas' => 'rice',
        'bigas' => 'rice',
        'humay' => 'rice',
        'kan-on' => 'rice',
        'kanon' => 'rice',
        'rice' => 'rice',
        'mantika' => 'cooking oil',
        'lana' => 'cooking oil',
        'cooking oil' => 'cooking oil',
        'vegetable oil' => 'cooking oil',
        'itlog' => 'egg',
        'eggs' => 'egg',
        'egg' => 'egg',
        'manok' => 'chicken',
        'chicken' => 'chicken',
        'baboy' => 'pork',
        'pork' => 'pork',
        'isda' => 'fish',
        'fish' => 'fish',
        'tinapay' => 'bread',
        'pandesal' => 'bread',
        'bread' => 'bread',
        'kape' => 'coffee',
        'coffee' => 'coffee',
        'tsaa' => 'tea',
        'tsa' => 'tea',
        'tea' => 'tea',
        'tubig' => 'water',
        'water' => 'water',
        'softdrinks' => 'soda',
        'soft drink' => 'soda',
        'coca cola' => 'soda',
        'coca-cola' => 'soda',
        'coke' => 'soda',
        'cola' => 'soda',
        'soda' => 'soda',
        'asin' => 'salt',
        'salt' => 'salt',
        'asukal' => 'sugar',
        'sugar' => 'sugar',
        'sabon' => 'soap',
        'soap' => 'soap',
        'sardinas' => 'sardines',
        'sardines' => 'sardines',
        'harina' => 'flour',
        'flour' => 'flour',
        'bawang' => 'garlic',
        'ahos' => 'garlic',
        'garlic' => 'garlic',
        'sibuyas' => 'onion',
        'onion' => 'onion',
        'kamatis' => 'tomato',
        'tomato' => 'tomato',
        'saging' => 'banana',
        'banana' => 'banana',
        'mangga' => 'mango',
        'mango' => 'mango',
        'keso' => 'cheese',
        'cheese' => 'cheese',
        'mantekiya' => 'butter',
        'mantequilla' => 'butter',
        'butter' => 'butter',
        'pansit' => 'pancit',
        'pancit' => 'pancit',
        'bihon' => 'bihon',
        'noodles' => 'noodles',
        'noodle' => 'noodles',
        'kalamansi' => 'calamansi',
        'calamansi' => 'calamansi',
    ],

    /*
    | Aliases that really appear in English catalog titles. Local words such as
    | "tuyo" are translated instead of matched against the product name.
    */
    'catalog_aliases' => [
        'soda' => ['coke', 'cola', 'coca cola', 'coca-cola', 'soft drink', 'softdrinks'],
        'egg' => ['eggs'],
        'noodles' => ['noodle'],
        'pancit' => ['pansit'],
        'bread' => ['pandesal'],
        'cooking oil' => ['vegetable oil'],
        'dried fish' => ['dried herring', 'bulad', 'daing'],
    ],

    'exclusion_aliases' => [
        'baka' => 'cow',
        'cow' => 'cow',
        'dairy' => 'cow',
    ],

    'cow_dairy_terms' => [
        'cow',
        'baka',
        'fresh milk',
        'full cream',
        'full-cream',
        'whole milk',
        'fresh cow',
    ],

    'plant_milk_terms' => [
        'vegan',
        'oat',
        'soy',
        'almond',
        'plant',
        'coconut',
        'goat',
        'kambing',
        'non-dairy',
        'dairy-free',
        'dairy free',
        'plant-based',
    ],

];
